apiVersion: v2
appVersion: '1.0'
description: Example for geoserver-cloud with datadir on a persistent volume
name: gs-cloud-statefulset
version: 0.1.0
dependencies:
  - name: geoservercloud
    repository: file://../../
    version: 0.1.0
