apiVersion: v2
appVersion: '1.0-RC11'
#appVersion: '1.0-SNAPSHOT'
description: A Helm chart for Geoserver-cloud
name: geoservercloud
version: 0.0.30
dependencies:
  - name: 'rabbitmq'
    version: 8.28.1
    repository: 'https://charts.bitnami.com/bitnami'
  - name: 'postgresql'
    version: 10.13.8
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
