apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}-config
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
  {{- if or .Values.global.annotations .Values.geoserver.config.annotations }}
  annotations:
    {{- if .Values.global.annotations }}
    {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end -}}
    {{- if .Values.geoserver.config.annotations }}
    {{- toYaml .Values.geoserver.config.annotations | nindent 4 }}
    {{- end -}}
  {{- end }}
spec:
  type: {{ .Values.geoserver.config.service.type }}
  ports:
    - port: {{ .Values.geoserver.config.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "geoserver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: config
