apiVersion: v2
appVersion: "1.0"
description: Example for geoserver-cloud with datadir
name: gs-cloud-datadir
version: 0.1.0
dependencies:
  - name: geoservercloud
    repository: file://../../
    version: 0.1.0
