apiVersion: v1
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: geoserver-datasources-env
data:
    jndi.yml: |-
        jndi:
          datasources:
            pgconfig:
              enabled: true
              schema: pgconfig
              wait-for-it: true
              wait-timeout: 10
              url: jdbc:postgresql://{{ .Release.Name }}-postgresql-hl:5432/postgres
              username: postgres
              password:  g30s3rv3r
              maximum-pool-size: 10
              minimum-idle: 2
              connection-timeout: 250
              idle-timeout: 60000
