apiVersion: v1
kind: ConfigMap
metadata:
    name: install-postgis-configmap
data:
    install-postgis.sh: |
        #!/bin/bash
        set -e
        echo "Creating PostGIS extension..."
        PGPASSWORD=$(echo $POSTGRES_PASSWORD) psql -U postgres -d postgres -c "CREATE EXTENSION IF NOT EXISTS postgis;"
