apiVersion: v2
appVersion: '1.0'
description: Example for geoserver-cloud with pgconfig
name: gs-cloud-pgconfig
version: 0.1.0
dependencies:
  - name: geoservercloud
    repository: file://../../
    version: 0.1.0
  # Postgres dependency used for pgconfig database and geoserver-acl database
  # Note: bitnami postgres chart is updated at initialization to add Postgis extension
  - name: 'postgresql'
    version: 15.5.2
    repository: 'oci://registry-1.docker.io/bitnamichartslegacy'
    condition: postgresql.enabled
