postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        # this should be replaced by your existing secret
        # existingSecret: your-secret-name
        postgresPassword: g30s3rv3r

additionalVolumes: &additional-volumes
  cache:
    emptyDir: {}

additionalVolumeMounts: &additional-volume-mounts
  /mnt/cache:
    name: 'cache'

# intentionally under-dimension it so it stresses out more easily
resources: &common-resources
  requests:
    memory: 512Mi
    cpu: 0.1
  limits:
    memory: 1Gi
    cpu: 2.0

common-spring-container-stuff: &common-spring-container-stuff
  resources:
    <<: *common-resources

env: &env-override
  PG_PASSWORD:
    type: secret
    name: 'gs-cloud-pgconfig-wms-hpa-postgresql'
    key: 'postgres-password'
  RABBITMQ_HOST:
    value: 'gs-cloud-common-rabbitmq'
  RABBITMQ_USER:
    value: 'geoserver'
  RABBITMQ_PASSWORD:
    type: secret
    name: 'gs-cloud-common-rabbitmq'
    key: 'rabbitmq-password'
  SPRING_PROFILES_ACTIVE:
    value: standalone,pgconfig
  GEOWEBCACHE_CACHE_DIR:
    value: '/mnt/cache'
  JAVA_OPTS:
    value: '$(JAVA_OPTS_DEFAULT) -XshowSettings:system'
  PGCONFIG_HOST:
    value: gs-cloud-pgconfig-wms-hpa-postgresql-hl
  PGCONFIG_PORT:
    value: '5432'
  PGCONFIG_DATABASE:
    value: postgres
  PGCONFIG_SCHEMA:
    value: pgconfig
  PGCONFIG_USERNAME:
    value: postgres
  PGCONFIG_PASSWORD:
    type: secret
    name: 'gs-cloud-pgconfig-wms-hpa-postgresql'
    key: 'postgres-password'
  PGCONFIG_MAXCONNECTIONS:
    value: '10'

additional-stuff: &additional-stuff
  volumes:
    <<: *additional-volumes
  containers:
    spring:
      <<: *common-spring-container-stuff
      env:
        <<: *env-override
      volumeMounts:
        <<: *additional-volume-mounts

geoservercloud:
  global:
    profile: standalone,pgconfig
    image:
      pullPolicy: IfNotPresent
  geoserver:
    ingress:
      enabled: true
      hostGroups:
        host1:
          tls:
            enabled: false
          hosts:
            - gscloud.local
    services:
      gateway:
        ingress:
          enabled: true
        <<: *additional-stuff
      webui:
        <<: *additional-stuff
      wms:
        replicaCount: 1
        hpa:
          enabled: true
          minReplicas: 1
          maxReplicas: 16
          metrics:
            - type: Resource
              resource:
                name: cpu
                target:
                  type: Utilization
                  averageUtilization: 70
        <<: *additional-stuff
      rest:
        replicaCount: 1
        <<: *additional-stuff
      wcs:
        enabled: false
        replicaCount: 0
        <<: *additional-stuff
      wfs:
        enabled: false
        replicaCount: 0
        <<: *additional-stuff
      gwc:
        enabled: false
        replicaCount: 0
        <<: *additional-stuff
      wps:
        enabled: false
        replicaCount: 0
        <<: *additional-stuff
      acl:
        enabled: false
