apiVersion: v2
appVersion: '1.0'
description: Example for geoserver-cloud with datadir
name: gs-cloud-datadir
version: 0.1.0
dependencies:
  - name: geoservercloud
    repository: https://camptocamp.github.io/helm-geoserver-cloud
    version: 0.7.1
  - name: rabbitmq
    version: 14.4.0
    repository: 'oci://ghcr.io/georchestra/bitnami-helm-charts'
    condition: rabbitmq.enabled
  - name: postgresql
    repository: 'oci://ghcr.io/georchestra/bitnami-helm-charts'
    version: 15.5.2
