name: Changelog Generator

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  changelog:
    name: Changelog Generator
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: |
            .github/changelog-generator-cache
          key: changelog-${{ steps.get-date.outputs.date }}
          restore-keys: |
            changelog-

      - name: Get config
        id: config
        run: echo "config=$(python -c 'print(__import__("json").dumps(__import__("yaml").load(open(".github/changelog-config.yaml"), Loader=__import__("yaml").SafeLoader)))')" >> $GITHUB_OUTPUT
      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}
          configureSections: ${{ steps.config.outputs.config }}
          cacheFile: .github/changelog-generator-cache
          unreleased: false

      - run: c2cciutils-checks --fix --check=prettier
      - id: status
        run: echo "status=$(git status --short)" >> $GITHUB_OUTPUT
      - run: |
          git add CHANGELOG.md
          git config --global user.email "ci@example.com"
          git config --global user.name "CI"
          git commit -m "Update the changelog"
          git checkout -b changelog-update
          git push origin changelog-update -f
          gh pr create --base=master --fill --label=chore || true
        env:
          GITHUB_TOKEN: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}
        if: steps.status.outputs.status != ''
